### ISSUE TITLE
Is this a MIT license project?

### ISSUE THREAD

**Issue by GeorgeS2019** [raphadesa/FileManager#1]
It is obvious you are passionate about Blazor. Could you offer your work to Blazor community with MIT licenses?

- https://github.com/raphadesa/BlazorInputMask
- https://github.com/raphadesa/BlazorModal
- https://github.com/raphadesa/BlazorAuth
- https://github.com/raphadesa/FileManager

**Comment by raphadesa** [comment]
Hello, sure, all of my GitHub content is under MIT license... Regards, Raphaël

**Comment by GeorgeS2019** [comment]
@raphadesa I urge you to state clearly and in a standard way they are MIT in all your projects. This helps MORE people to find your projects and recommend your projects to others.

**Comment by raphadesa** [comment]
Hi George, thanks a lot for letting me know, as I wasn't aware of this. I'll update all my projects to MIT as soon as I'm back from vacation ;) 

Regards,

Raphael

**Comment by raphadesa** [comment]
Hi, it's done ! Thanks a lot for letting me know, and good coding fun !

Regards,

Raphael
